//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogDataStatusHistory
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> StopPlayPause { get; set; }
        public Nullable<int> OperationType { get; set; }
        public Nullable<int> OperationStatus { get; set; }
        public Nullable<int> OperationMode { get; set; }
        public Nullable<int> StateCondition { get; set; }
        public System.DateTime PeriodStart { get; set; }
        public System.DateTime PeriodEnd { get; set; }
    }
}
