//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class YardMachineMaterial
    {
        public System.DateTime Datetime { get; set; }
        public string Name { get; set; }
        public Nullable<double> Flow { get; set; }
        public Nullable<double> FlowSetpoint { get; set; }
        public Nullable<double> Pressure { get; set; }
        public Nullable<double> PressureSetpoint { get; set; }
        public Nullable<double> OverloadValue { get; set; }
        public Nullable<int> OperationStatus { get; set; }
        public Nullable<int> OperationType { get; set; }
        public Nullable<int> OperationMode { get; set; }
    }
}
